#!/bin/bash
CALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DYLD_LIBRARY_PATH_OLD=$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH="$CALLDIR/../php/lib"
cd "$CALLDIR/../php"
bin/php -S 127.0.0.1:57187 -t ../Resources/chrome/webapp -c php.ini -n &
cd -
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH_OLD
"$CALLDIR/app-bin" "$CALLDIR/../Resources/application.ini" "$@"
killall php

